# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arm_hand_deployment/franka/proto/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='arm_hand_deployment/franka/proto/service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.arm_hand_deployment/franka/proto/service.proto\"\x07\n\x05\x45mpty\"Q\n\x1bMoveToJointPositionsRequest\x12\x11\n\tpositions\x18\x01 \x03(\x02\x12\x1f\n\x17num_interpolation_steps\x18\x02 \x01(\x05\"#\n\x0eJointPositions\x12\x11\n\tpositions\x18\x01 \x03(\x02\"/\n\x04Pose\x12\x0c\n\x04pose\x18\x01 \x03(\x02\x12\x19\n\x11return_joint_traj\x18\x02 \x01(\x08\"\x1f\n\tDeltaPose\x12\x12\n\ndelta_pose\x18\x01 \x03(\x02\"\x1e\n\rGripperAction\x12\r\n\x05value\x18\x01 \x01(\x02\"$\n\x0eGripperMessage\x12\x12\n\nis_grasped\x18\x01 \x01(\x08\":\n\x06Result\x12\x11\n\x02ok\x18\x01 \x01(\x0b\x32\x03.OkH\x00\x12\x13\n\x03\x65rr\x18\x02 \x01(\x0b\x32\x04.ErrH\x00\x42\x08\n\x06result\"\x04\n\x02Ok\"\x16\n\x03\x45rr\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe0\x03\n\rFrankaService\x12\x18\n\x05Start\x12\x06.Empty\x1a\x07.Result\x12\x17\n\x04Stop\x12\x06.Empty\x1a\x07.Result\x12,\n\x11GetJointPositions\x12\x06.Empty\x1a\x0f.JointPositions\x12#\n\x12GetEndEffectorPose\x12\x06.Empty\x1a\x05.Pose\x12=\n\x14MoveToJointPositions\x12\x1c.MoveToJointPositionsRequest\x1a\x07.Result\x12\'\n\x15MoveToEndEffectorPose\x12\x05.Pose\x1a\x07.Result\x12+\n\x10SetGripperAction\x12\x0e.GripperAction\x1a\x07.Result\x12\x33\n\x1c\x43ontrollDeltaEndEffectorPose\x12\n.DeltaPose\x1a\x07.Result\x12\x31\n\x15\x43ontrolJointPositions\x12\x0f.JointPositions\x1a\x07.Result\x12,\n\x11GetGripperMessage\x12\x06.Empty\x1a\x0f.GripperMessage\x12\x1e\n\x0bStopGripper\x12\x06.Empty\x1a\x07.Resultb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=57,
)


_MOVETOJOINTPOSITIONSREQUEST = _descriptor.Descriptor(
  name='MoveToJointPositionsRequest',
  full_name='MoveToJointPositionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='MoveToJointPositionsRequest.positions', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_interpolation_steps', full_name='MoveToJointPositionsRequest.num_interpolation_steps', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=140,
)


_JOINTPOSITIONS = _descriptor.Descriptor(
  name='JointPositions',
  full_name='JointPositions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='JointPositions.positions', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=177,
)


_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='Pose.pose', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='return_joint_traj', full_name='Pose.return_joint_traj', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=226,
)


_DELTAPOSE = _descriptor.Descriptor(
  name='DeltaPose',
  full_name='DeltaPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='delta_pose', full_name='DeltaPose.delta_pose', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=259,
)


_GRIPPERACTION = _descriptor.Descriptor(
  name='GripperAction',
  full_name='GripperAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GripperAction.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=291,
)


_GRIPPERMESSAGE = _descriptor.Descriptor(
  name='GripperMessage',
  full_name='GripperMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_grasped', full_name='GripperMessage.is_grasped', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=329,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='Result.ok', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err', full_name='Result.err', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='Result.result',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=331,
  serialized_end=389,
)


_OK = _descriptor.Descriptor(
  name='Ok',
  full_name='Ok',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=395,
)


_ERR = _descriptor.Descriptor(
  name='Err',
  full_name='Err',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='Err.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=419,
)

_RESULT.fields_by_name['ok'].message_type = _OK
_RESULT.fields_by_name['err'].message_type = _ERR
_RESULT.oneofs_by_name['result'].fields.append(
  _RESULT.fields_by_name['ok'])
_RESULT.fields_by_name['ok'].containing_oneof = _RESULT.oneofs_by_name['result']
_RESULT.oneofs_by_name['result'].fields.append(
  _RESULT.fields_by_name['err'])
_RESULT.fields_by_name['err'].containing_oneof = _RESULT.oneofs_by_name['result']
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['MoveToJointPositionsRequest'] = _MOVETOJOINTPOSITIONSREQUEST
DESCRIPTOR.message_types_by_name['JointPositions'] = _JOINTPOSITIONS
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['DeltaPose'] = _DELTAPOSE
DESCRIPTOR.message_types_by_name['GripperAction'] = _GRIPPERACTION
DESCRIPTOR.message_types_by_name['GripperMessage'] = _GRIPPERMESSAGE
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Ok'] = _OK
DESCRIPTOR.message_types_by_name['Err'] = _ERR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'arm_hand_deployment.franka.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

MoveToJointPositionsRequest = _reflection.GeneratedProtocolMessageType('MoveToJointPositionsRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVETOJOINTPOSITIONSREQUEST,
  '__module__' : 'arm_hand_deployment.franka.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:MoveToJointPositionsRequest)
  })
_sym_db.RegisterMessage(MoveToJointPositionsRequest)

JointPositions = _reflection.GeneratedProtocolMessageType('JointPositions', (_message.Message,), {
  'DESCRIPTOR' : _JOINTPOSITIONS,
  '__module__' : 'arm_hand_deployment.franka.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:JointPositions)
  })
_sym_db.RegisterMessage(JointPositions)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {
  'DESCRIPTOR' : _POSE,
  '__module__' : 'arm_hand_deployment.franka.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:Pose)
  })
_sym_db.RegisterMessage(Pose)

DeltaPose = _reflection.GeneratedProtocolMessageType('DeltaPose', (_message.Message,), {
  'DESCRIPTOR' : _DELTAPOSE,
  '__module__' : 'arm_hand_deployment.franka.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:DeltaPose)
  })
_sym_db.RegisterMessage(DeltaPose)

GripperAction = _reflection.GeneratedProtocolMessageType('GripperAction', (_message.Message,), {
  'DESCRIPTOR' : _GRIPPERACTION,
  '__module__' : 'arm_hand_deployment.franka.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:GripperAction)
  })
_sym_db.RegisterMessage(GripperAction)

GripperMessage = _reflection.GeneratedProtocolMessageType('GripperMessage', (_message.Message,), {
  'DESCRIPTOR' : _GRIPPERMESSAGE,
  '__module__' : 'arm_hand_deployment.franka.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:GripperMessage)
  })
_sym_db.RegisterMessage(GripperMessage)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'arm_hand_deployment.franka.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)

Ok = _reflection.GeneratedProtocolMessageType('Ok', (_message.Message,), {
  'DESCRIPTOR' : _OK,
  '__module__' : 'arm_hand_deployment.franka.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:Ok)
  })
_sym_db.RegisterMessage(Ok)

Err = _reflection.GeneratedProtocolMessageType('Err', (_message.Message,), {
  'DESCRIPTOR' : _ERR,
  '__module__' : 'arm_hand_deployment.franka.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:Err)
  })
_sym_db.RegisterMessage(Err)



_FRANKASERVICE = _descriptor.ServiceDescriptor(
  name='FrankaService',
  full_name='FrankaService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=422,
  serialized_end=902,
  methods=[
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='FrankaService.Start',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Stop',
    full_name='FrankaService.Stop',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetJointPositions',
    full_name='FrankaService.GetJointPositions',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_JOINTPOSITIONS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetEndEffectorPose',
    full_name='FrankaService.GetEndEffectorPose',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_POSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MoveToJointPositions',
    full_name='FrankaService.MoveToJointPositions',
    index=4,
    containing_service=None,
    input_type=_MOVETOJOINTPOSITIONSREQUEST,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MoveToEndEffectorPose',
    full_name='FrankaService.MoveToEndEffectorPose',
    index=5,
    containing_service=None,
    input_type=_POSE,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetGripperAction',
    full_name='FrankaService.SetGripperAction',
    index=6,
    containing_service=None,
    input_type=_GRIPPERACTION,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ControllDeltaEndEffectorPose',
    full_name='FrankaService.ControllDeltaEndEffectorPose',
    index=7,
    containing_service=None,
    input_type=_DELTAPOSE,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ControlJointPositions',
    full_name='FrankaService.ControlJointPositions',
    index=8,
    containing_service=None,
    input_type=_JOINTPOSITIONS,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetGripperMessage',
    full_name='FrankaService.GetGripperMessage',
    index=9,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_GRIPPERMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopGripper',
    full_name='FrankaService.StopGripper',
    index=10,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRANKASERVICE)

DESCRIPTOR.services_by_name['FrankaService'] = _FRANKASERVICE

# @@protoc_insertion_point(module_scope)
