# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arm_hand_deployment/franka/proto/service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'arm_hand_deployment/franka/proto/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.arm_hand_deployment/franka/proto/service.proto\"\x07\n\x05\x45mpty\"#\n\x0eJointPositions\x12\x11\n\tpositions\x18\x01 \x03(\x02\"\x14\n\x04Pose\x12\x0c\n\x04pose\x18\x01 \x03(\x02\"\x1f\n\tDeltaPose\x12\x12\n\ndelta_pose\x18\x01 \x03(\x02\"\x1e\n\rGripperAction\x12\r\n\x05value\x18\x01 \x01(\x02\"$\n\x0eGripperMessage\x12\x12\n\nis_grasped\x18\x01 \x01(\x08\":\n\x06Result\x12\x11\n\x02ok\x18\x01 \x01(\x0b\x32\x03.OkH\x00\x12\x13\n\x03\x65rr\x18\x02 \x01(\x0b\x32\x04.ErrH\x00\x42\x08\n\x06result\"\x04\n\x02Ok\"\x16\n\x03\x45rr\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb3\x03\n\rFrankaService\x12\x18\n\x05Start\x12\x06.Empty\x1a\x07.Result\x12\x17\n\x04Stop\x12\x06.Empty\x1a\x07.Result\x12,\n\x11GetJointPositions\x12\x06.Empty\x1a\x0f.JointPositions\x12#\n\x12GetEndEffectorPose\x12\x06.Empty\x1a\x05.Pose\x12\x30\n\x14MoveToJointPositions\x12\x0f.JointPositions\x1a\x07.Result\x12\'\n\x15MoveToEndEffectorPose\x12\x05.Pose\x1a\x07.Result\x12+\n\x10SetGripperAction\x12\x0e.GripperAction\x1a\x07.Result\x12\x33\n\x1c\x43ontrollDeltaEndEffectorPose\x12\n.DeltaPose\x1a\x07.Result\x12\x31\n\x15\x43ontrolJointPositions\x12\x0f.JointPositions\x1a\x07.Result\x12,\n\x11GetGripperMessage\x12\x06.Empty\x1a\x0f.GripperMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arm_hand_deployment.franka.proto.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=50
  _globals['_EMPTY']._serialized_end=57
  _globals['_JOINTPOSITIONS']._serialized_start=59
  _globals['_JOINTPOSITIONS']._serialized_end=94
  _globals['_POSE']._serialized_start=96
  _globals['_POSE']._serialized_end=116
  _globals['_DELTAPOSE']._serialized_start=118
  _globals['_DELTAPOSE']._serialized_end=149
  _globals['_GRIPPERACTION']._serialized_start=151
  _globals['_GRIPPERACTION']._serialized_end=181
  _globals['_GRIPPERMESSAGE']._serialized_start=183
  _globals['_GRIPPERMESSAGE']._serialized_end=219
  _globals['_RESULT']._serialized_start=221
  _globals['_RESULT']._serialized_end=279
  _globals['_OK']._serialized_start=281
  _globals['_OK']._serialized_end=285
  _globals['_ERR']._serialized_start=287
  _globals['_ERR']._serialized_end=309
  _globals['_FRANKASERVICE']._serialized_start=312
  _globals['_FRANKASERVICE']._serialized_end=747
# @@protoc_insertion_point(module_scope)
