# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from arm_hand_deployment.franka.proto import service_pb2 as arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in arm_hand_deployment/franka/proto/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrankaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/FrankaService/Start',
                request_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/FrankaService/Stop',
                request_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.GetJointPositions = channel.unary_unary(
                '/FrankaService/GetJointPositions',
                request_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.JointPositions.FromString,
                _registered_method=True)
        self.GetEndEffectorPose = channel.unary_unary(
                '/FrankaService/GetEndEffectorPose',
                request_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Pose.FromString,
                _registered_method=True)
        self.MoveToJointPositions = channel.unary_unary(
                '/FrankaService/MoveToJointPositions',
                request_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.MoveToEndEffectorPose = channel.unary_unary(
                '/FrankaService/MoveToEndEffectorPose',
                request_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Pose.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.SetGripperAction = channel.unary_unary(
                '/FrankaService/SetGripperAction',
                request_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.GripperAction.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.ControllDeltaEndEffectorPose = channel.unary_unary(
                '/FrankaService/ControllDeltaEndEffectorPose',
                request_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.DeltaPose.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.ControlJointPositions = channel.unary_unary(
                '/FrankaService/ControlJointPositions',
                request_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)


class FrankaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """RPC to start the robot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """RPC to stop the robot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJointPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEndEffectorPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveToJointPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveToEndEffectorPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGripperAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControllDeltaEndEffectorPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlJointPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrankaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.FromString,
                    response_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.FromString,
                    response_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'GetJointPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointPositions,
                    request_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.FromString,
                    response_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
            ),
            'GetEndEffectorPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEndEffectorPose,
                    request_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.FromString,
                    response_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Pose.SerializeToString,
            ),
            'MoveToJointPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveToJointPositions,
                    request_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.JointPositions.FromString,
                    response_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'MoveToEndEffectorPose': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveToEndEffectorPose,
                    request_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Pose.FromString,
                    response_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'SetGripperAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGripperAction,
                    request_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.GripperAction.FromString,
                    response_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'ControllDeltaEndEffectorPose': grpc.unary_unary_rpc_method_handler(
                    servicer.ControllDeltaEndEffectorPose,
                    request_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.DeltaPose.FromString,
                    response_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'ControlJointPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlJointPositions,
                    request_deserializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.JointPositions.FromString,
                    response_serializer=arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FrankaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FrankaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrankaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaService/Start',
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.SerializeToString,
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaService/Stop',
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.SerializeToString,
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJointPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaService/GetJointPositions',
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.SerializeToString,
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.JointPositions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEndEffectorPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaService/GetEndEffectorPose',
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Empty.SerializeToString,
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Pose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveToJointPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaService/MoveToJointPositions',
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveToEndEffectorPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaService/MoveToEndEffectorPose',
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Pose.SerializeToString,
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGripperAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaService/SetGripperAction',
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.GripperAction.SerializeToString,
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControllDeltaEndEffectorPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaService/ControllDeltaEndEffectorPose',
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.DeltaPose.SerializeToString,
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlJointPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaService/ControlJointPositions',
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
            arm__hand__deployment_dot_franka_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
