# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from arm_hand_deployment.franka_allegro.proto import service_pb2 as arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in arm_hand_deployment/franka_allegro/proto/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrankaAllegroServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/FrankaAllegroService/Start',
                request_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/FrankaAllegroService/Stop',
                request_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.GetJointPositions = channel.unary_unary(
                '/FrankaAllegroService/GetJointPositions',
                request_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.FromString,
                _registered_method=True)
        self.GetEndEffectorPose = channel.unary_unary(
                '/FrankaAllegroService/GetEndEffectorPose',
                request_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Pose.FromString,
                _registered_method=True)
        self.MoveToJointPositions = channel.unary_unary(
                '/FrankaAllegroService/MoveToJointPositions',
                request_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.ArmMoveToJointPositions = channel.unary_unary(
                '/FrankaAllegroService/ArmMoveToJointPositions',
                request_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.ArmMoveToEndEffectorPose = channel.unary_unary(
                '/FrankaAllegroService/ArmMoveToEndEffectorPose',
                request_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Pose.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.HandMoveToJointPositions = channel.unary_unary(
                '/FrankaAllegroService/HandMoveToJointPositions',
                request_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.ControlJointPositions = channel.unary_unary(
                '/FrankaAllegroService/ControlJointPositions',
                request_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.ControlArmEEPoseHandDeltaJointPositions = channel.unary_unary(
                '/FrankaAllegroService/ControlArmEEPoseHandDeltaJointPositions',
                request_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.ArmEEPoseHandJointPositions.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)
        self.ControlArmEEPoseHandJointPositions = channel.unary_unary(
                '/FrankaAllegroService/ControlArmEEPoseHandJointPositions',
                request_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.ArmEEPoseHandJointPositions.SerializeToString,
                response_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
                _registered_method=True)


class FrankaAllegroServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """RPC to start the robot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """RPC to stop the robot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJointPositions(self, request, context):
        """Get joint positions (7 arm + 16 hand).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEndEffectorPose(self, request, context):
        """Get end effector pose (3 xyz + 3 rpy).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveToJointPositions(self, request, context):
        """Move to specific joint positions (7 arm + 16 hand).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArmMoveToJointPositions(self, request, context):
        """Move to specific joint positions (7 arm joints).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArmMoveToEndEffectorPose(self, request, context):
        """Move to a specific end effector pose (3 xyz + 3 rpy).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandMoveToJointPositions(self, request, context):
        """Move to specific joint positions (16 hand joints).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlJointPositions(self, request, context):
        """(7 arm + 16 hand).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlArmEEPoseHandDeltaJointPositions(self, request, context):
        """Absolute EE pose (xyz+rpy); delta joint positions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlArmEEPoseHandJointPositions(self, request, context):
        """Absolute EE pose (xyz+rpy); joint positions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrankaAllegroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.FromString,
                    response_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.FromString,
                    response_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'GetJointPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointPositions,
                    request_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.FromString,
                    response_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
            ),
            'GetEndEffectorPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEndEffectorPose,
                    request_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.FromString,
                    response_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Pose.SerializeToString,
            ),
            'MoveToJointPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveToJointPositions,
                    request_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.FromString,
                    response_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'ArmMoveToJointPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ArmMoveToJointPositions,
                    request_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.FromString,
                    response_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'ArmMoveToEndEffectorPose': grpc.unary_unary_rpc_method_handler(
                    servicer.ArmMoveToEndEffectorPose,
                    request_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Pose.FromString,
                    response_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'HandMoveToJointPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.HandMoveToJointPositions,
                    request_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.FromString,
                    response_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'ControlJointPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlJointPositions,
                    request_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.FromString,
                    response_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'ControlArmEEPoseHandDeltaJointPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlArmEEPoseHandDeltaJointPositions,
                    request_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.ArmEEPoseHandJointPositions.FromString,
                    response_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
            'ControlArmEEPoseHandJointPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlArmEEPoseHandJointPositions,
                    request_deserializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.ArmEEPoseHandJointPositions.FromString,
                    response_serializer=arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FrankaAllegroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FrankaAllegroService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrankaAllegroService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaAllegroService/Start',
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.SerializeToString,
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaAllegroService/Stop',
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.SerializeToString,
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJointPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaAllegroService/GetJointPositions',
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.SerializeToString,
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEndEffectorPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaAllegroService/GetEndEffectorPose',
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Empty.SerializeToString,
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Pose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveToJointPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaAllegroService/MoveToJointPositions',
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArmMoveToJointPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaAllegroService/ArmMoveToJointPositions',
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArmMoveToEndEffectorPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaAllegroService/ArmMoveToEndEffectorPose',
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Pose.SerializeToString,
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandMoveToJointPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaAllegroService/HandMoveToJointPositions',
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlJointPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaAllegroService/ControlJointPositions',
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.JointPositions.SerializeToString,
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlArmEEPoseHandDeltaJointPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaAllegroService/ControlArmEEPoseHandDeltaJointPositions',
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.ArmEEPoseHandJointPositions.SerializeToString,
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlArmEEPoseHandJointPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FrankaAllegroService/ControlArmEEPoseHandJointPositions',
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.ArmEEPoseHandJointPositions.SerializeToString,
            arm__hand__deployment_dot_franka__allegro_dot_proto_dot_service__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
