# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arm_hand_deployment/franka_allegro/proto/service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'arm_hand_deployment/franka_allegro/proto/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6arm_hand_deployment/franka_allegro/proto/service.proto\"\x07\n\x05\x45mpty\"\x1f\n\rGravityVector\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"#\n\x0eJointPositions\x12\x11\n\tpositions\x18\x01 \x03(\x02\"\x14\n\x04Pose\x12\x0c\n\x04pose\x18\x01 \x03(\x02\"D\n\x1b\x41rmEEPoseHandJointPositions\x12\x0c\n\x04pose\x18\x01 \x03(\x02\x12\x17\n\x0fjoint_positions\x18\x02 \x03(\x02\":\n\x06Result\x12\x11\n\x02ok\x18\x01 \x01(\x0b\x32\x03.OkH\x00\x12\x13\n\x03\x65rr\x18\x02 \x01(\x0b\x32\x04.ErrH\x00\x42\x08\n\x06result\"\x04\n\x02Ok\"\x16\n\x03\x45rr\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe4\x04\n\x14\x46rankaAllegroService\x12\x18\n\x05Start\x12\x06.Empty\x1a\x07.Result\x12\x17\n\x04Stop\x12\x06.Empty\x1a\x07.Result\x12,\n\x11GetJointPositions\x12\x06.Empty\x1a\x0f.JointPositions\x12#\n\x12GetEndEffectorPose\x12\x06.Empty\x1a\x05.Pose\x12+\n\x10SetGravityVector\x12\x0e.GravityVector\x1a\x07.Result\x12\x30\n\x14MoveToJointPositions\x12\x0f.JointPositions\x1a\x07.Result\x12\x33\n\x17\x41rmMoveToJointPositions\x12\x0f.JointPositions\x1a\x07.Result\x12*\n\x18\x41rmMoveToEndEffectorPose\x12\x05.Pose\x1a\x07.Result\x12\x34\n\x18HandMoveToJointPositions\x12\x0f.JointPositions\x1a\x07.Result\x12\x31\n\x15\x43ontrolJointPositions\x12\x0f.JointPositions\x1a\x07.Result\x12P\n\'ControlArmEEPoseHandDeltaJointPositions\x12\x1c.ArmEEPoseHandJointPositions\x1a\x07.Result\x12K\n\"ControlArmEEPoseHandJointPositions\x12\x1c.ArmEEPoseHandJointPositions\x1a\x07.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arm_hand_deployment.franka_allegro.proto.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=58
  _globals['_EMPTY']._serialized_end=65
  _globals['_GRAVITYVECTOR']._serialized_start=67
  _globals['_GRAVITYVECTOR']._serialized_end=98
  _globals['_JOINTPOSITIONS']._serialized_start=100
  _globals['_JOINTPOSITIONS']._serialized_end=135
  _globals['_POSE']._serialized_start=137
  _globals['_POSE']._serialized_end=157
  _globals['_ARMEEPOSEHANDJOINTPOSITIONS']._serialized_start=159
  _globals['_ARMEEPOSEHANDJOINTPOSITIONS']._serialized_end=227
  _globals['_RESULT']._serialized_start=229
  _globals['_RESULT']._serialized_end=287
  _globals['_OK']._serialized_start=289
  _globals['_OK']._serialized_end=293
  _globals['_ERR']._serialized_start=295
  _globals['_ERR']._serialized_end=317
  _globals['_FRANKAALLEGROSERVICE']._serialized_start=320
  _globals['_FRANKAALLEGROSERVICE']._serialized_end=932
# @@protoc_insertion_point(module_scope)
